# Generated by Django 4.2.1 on 2023-06-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_groupsposts_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photos/%Y/%m/%d'),
        ),
    ]
